services:
  api:
    build:
      context: .
      dockerfile: apps/tasker-api/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:passwd@mongo:27017/tasker?authSource=admin
      - JWT_SECRET=provide_secret_key
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    command: ["mongod", "--quiet"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
#    ports:
#      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
